// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeaProject.DataAccess.Data;

#nullable disable

namespace TeaProject.DataAccess.Migrations
{
    [DbContext(typeof(TeaProject0504Context))]
    [Migration("20240507152319_AddProductTableSecond")]
    partial class AddProductTableSecond
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeaProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC07E15D4861");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("TeaProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "紅茶",
                            Price = 30.0,
                            Size = "大杯",
                            Temperature = "熱飲"
                        },
                        new
                        {
                            Id = 2,
                            Name = "綠茶",
                            Price = 30.0,
                            Size = "大杯",
                            Temperature = "熱飲"
                        },
                        new
                        {
                            Id = 3,
                            Name = "奶茶",
                            Price = 40.0,
                            Size = "大杯",
                            Temperature = "熱飲"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
